Pallet updater --- Added pallet to runtime
CherryNetwork/Cherry-Node pull request #55
Opened 2022-04-01 19:19 UTC by Chubek

- Added pallet_runtime to `runtime/cargo.toml` of `/bin`. This includes the system dependencies, std, benchmark e tc.
- Imported pallet_runtime for us in `runtime/src/lib.rs`
- Added pallet_runtime config impl in the aforementioned file
- Added pallet_runtime to `construct_runtime` macro.

2022-04-01 19:22 UTC, charmitro requested changes
Please run `cargo fmt` before pushing changes.

2022-04-01 19:22 UTC, charmitro commented on bin/node/runtime/Cargo.toml
> +
Unnecessary line

2022-04-01 19:22 UTC, charmitro commented on bin/node/runtime/Cargo.toml
> +
Unnecessary line

2022-04-01 19:22 UTC, charmitro commented on bin/node/runtime/src/lib.rs
> +
Unnecessary line

2022-04-01 19:22 UTC, charmitro commented on bin/node/runtime/src/lib.rs
> +
Unnecessary line

2022-04-01 19:22 UTC, charmitro commented on bin/node/runtime/src/lib.rs
> +
Unnecessary line

2022-04-01 19:22 UTC, charmitro commented on bin/node/runtime/src/lib.rs
> +
Unnecessary line

2022-04-12 15:30 UTC, charmitro commented
@zycon91 @Chubek Please make sure this work as intended and move it out of DRAFT mode once you're sure about it.

2022-04-13 08:57 UTC, Chubek commented
I am marking this to review. Me and @zycon91 ran and tested it. Fotis wrote the fixes which we can see in pallet-updater-fixes. Time to set it for review.

2022-04-13 10:59 UTC, charmitro approved these changes

2022-04-13 10:59 UTC, merged