Pallet updater benchmark test --- added 6 tests and [soon] benchmarks
CherryNetwork/Cherry-Node pull request #63
Opened 2022-04-11 08:53 UTC by Chubek

Currently 6 tests have been added. All tests passing.

There is a problem that I think will be better for the issues section, but `System::event()` is for some reason entirely empty, making me unable to write event tests.

The tests are:

1. `test_genesis_work`
2. `test_add_member_work`
3. `test_remove_member_work`
4. `test_propose_code_work`
5. `test_vote_code_work`
6. test_close_vote_work

2022-04-11 12:22 UTC, charmitro requested changes

2022-04-11 12:22 UTC, charmitro commented on bin/node/pallets/pallet-updater/src/tests.rs
> +frame_support::construct_runtime!(
`construct_runtime!` along with the config implementations should be in the `mock.rs` file. We should always follow the structure of others pallets.

2022-04-11 12:23 UTC, charmitro requested changes

2022-04-11 12:23 UTC, charmitro commented on bin/node/pallets/pallet-updater/src/tests.rs
> +}
This code should be in its own file called `mock.rs` just like we do for the other pallets.

2022-04-11 13:05 UTC, zycon91 commented
Shouldn't we include some ```should_fail``` tests to check if the errors are working as intended? I think you have "included" those errors check in your ```should_work``` tests with the ```assert_noop!``` you are using. I think we should separate the tests to ```should_work``` and ```should_fail```.

Example of a ```should_fail``` test:
https://github.com/CherryNetwork/Cherry-Node/blob/fc9a103a101540679f1e4e340f3d5433a1192f5b/frame/treasury/src/tests.rs#L246-L251

2022-04-11 13:11 UTC, charmitro commented
> Shouldn't we include some `should_fail` tests to check if the errors are working as intended? I think you have "included" those errors check in your `should_work` tests with the `assert_noop!` you are using. I think we should separate the tests to `should_work` and `should_fail`.
> 
> Example of a `should_fail` test:
> 
> https://github.com/CherryNetwork/Cherry-Node/blob/fc9a103a101540679f1e4e340f3d5433a1192f5b/frame/treasury/src/tests.rs#L246-L251

Totally agree with this @Chubek

2022-04-11 17:14 UTC, zycon91 approved these changes
Looks a lot cleaner now!

2022-04-12 10:59 UTC, charmitro reviewed
@zycon91 Make sure to test if these work as intendet. I will merge on your call.

2022-04-12 10:59 UTC, charmitro approved these changes

2022-04-12 13:26 UTC, charmitro approved these changes

2022-04-12 13:26 UTC, merged